config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	root 'sessions#new'
	
	# get '/login', to: 'static_pages#login'
	get '/signup', to: 'users#new'
	get '/all', to: 'users#all'
	
	get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'
	post '/guest', to: 'guest_sessions#create'
	
	resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  has_one :microposts, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
end

app/controllers/guest_sessions_controller.rb
class GuestSessionsController < ApplicationController
	# skip_before_action :login_required

  def create
    user = User.find_by(email: 'example@railstutorial.org')
    log_in(user)
    flash[:success] = 'ゲストユーザーでログインしました'
    flash[:warning] = 'よろしくお願いします！'
    redirect_to all_path
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to all_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def login
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:all, :show]
	before_action :correct_user,   only: [:show]
	
	def show
		@user = User.find(params[:id])
		@micropost = Micropost.find(@user.id)
	end
	
	def new
		@user = User.new(params[:id])
	end
	
	def create
		@user = User.new(user_params)
		if @user.save
			log_in @user
			flash[:success] = "ようこそ、ポートフォリオの森へ"
			redirect_to all_path
		else
			render 'new'
		end
	end
	
	def all
		@users = User.paginate(page: params[:page])
	end
	
	private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation)
    end
    
    # beforeアクション

    # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        flash[:danger] = "ログインしてください"
        redirect_to root_url
      end
    end
    
    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      unless current_user?(@user)
        flash[:danger] = "閲覧権限がありません"
        redirect_to all_path
      end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guest_sessions_helper.rb
module GuestSessionsHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # 現在ログイン中のユーザーを返す（いる場合）
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end
  
  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  # 渡されたユーザーがカレントユーザーであればtrueを返す
  def current_user?(user)
    user && user == current_user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "login", login_path %></li>
      <li><%= link_to "Sign up", signup_path %></li>
      <li>
        <a href="https://aforestlife.com/guides/animal-crossing-town-name-ideas-and-methods/">A Forest Life</a>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "ポートフォリオの森", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right fixed-top">
          
        <% if logged_in? %>
          <li><%= link_to "ユーザー一覧",all_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "ポートフォリオ", current_user %></li>
              <li><%= link_to "設定", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "サインアップ", signup_path %></li>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
        
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortforioApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'layouts/shim' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <h1>おいでよポートフォリオの森</h1>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="gazou">
    <%= link_to image_tag("atsumori.png", alt: "atsumori.png", class: "image",width: "80%"),
                 "https://www.nintendo.co.jp/switch/acbaa/index.html" %>
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/microposts/_show.html.erb
	<p class="content"><%= @micropost.content %></p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/login.html.erb
<!--<h1>ログイン</h1>-->

<!--<div class="row">-->
<!--  <div class="col-md-6 col-md-offset-3">-->
<!--    <%= form_with(model: @user, local: true) do |f| %>-->

<!--      <%= f.label :name, "名前" %>-->
<!--      <%= f.text_field :name, class: 'form-control' %>-->

<!--      <%= f.label :email, "メールアドレス" %>-->
<!--      <%= f.email_field :email, class: 'form-control' %>-->

<!--      <%= f.label :password, "パスワード" %>-->
<!--      <%= f.password_field :password, class: 'form-control' %>-->

<!--      <%= f.label :password_confirmation, "パスワード確認" %>-->
<!--      <%= f.password_field :password_confirmation, class: 'form-control' %>-->

<!--      <%= f.submit "ログインする", class: "btn btn-primary" %>-->
<!--      <div class="center jumbotron">-->
<!--        <%= link_to "新規アカウント作成", signup_path, class: "btn btn-lg btn-primary" %>-->
<!--      </div>-->
<!--    <% end %>-->
<!--    <%= link_to 'ゲストユーザー', guest_path, method: :post, class: 'btn btn-success' %>-->
<!--  </div>-->
<!--</div>-->

app/views/static_pages/top.html.erb
<h1>ログイン</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "ログインする", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/all.html.erb
<h1>ユーザー一覧</h1>

<div class="page">
<%= will_paginate %>
</div>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <h3><%= link_to user.name, user %></h3>
    </li>
  <% end %>
</ul>

<div class="page">
<%= will_paginate %>
</div>

<div class="center jumbotron">
    <%= link_to "TOP(ログイン)ページに戻る", login_path, class: "btn btn-lg btn-primary" %> 
</div>

app/views/users/new.html.erb
<h1>サインアップ</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "アカウント作成する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>ポートフォリオページ</h1>
      <h1>
        <%= @user.name %>
      </h1>
      <div class="micropost">
        <% if @micropost %>
            <%= render 'microposts/show' %>
        <% end %>
      </div>
      <div class="center jumbotron">
        <%= link_to "TOPページ(ログイン)に戻る", login_path, class: "btn btn-lg btn-primary" %> 
			</div>
  